export const EXPERIENCE = [
  {
    role: "Senior Front End Developer",
    company: "mod.io",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "Australia",
    dateFrom: "01-02-2021",
    dateTo: null,
  },
  {
    role: "Co-Founder & Director",
    company: "Linked Entity Limted",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2016",
    dateTo: "01-05-2022",
  },
  {
    role: "Co-Founder & Director",
    company: "Gig Ocean",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2018",
    dateTo: "01-01-2022",
  },
  {
    role: "Senior Front End Developer",
    company: "Icon Agency",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-12-2016",
    dateTo: "01-02-2021",
  },
  {
    role: "Front End Developer",
    company: "IO Stuidos LTD",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-06-2013",
    dateTo: "01-10-2016",
  },
  {
    role: "Web Developer",
    company: "NFU Mutual",
    icon: "https://picsum.photos/200",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-09-2007",
    dateTo: "01-06-2013",
  },
];
