export const EXPERIENCE = [
  {
    role: "Senior Front End Developer",
    company: "mod.io",
    icon: "images/modio.jpeg",
    type: "Full-time",
    country: "Australia",
    dateFrom: "01-02-2021",
    dateTo: null,
    link: "https://beta.mod.io/",
  },
  {
    role: "Co-Founder & Director",
    company: "Linked Entity Limted",
    icon: "images/linkedentity.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2016",
    dateTo: "01-05-2022",
    link: "http://www.linkedentity.com/",
  },
  {
    role: "Co-Founder & Director",
    company: "Gig Ocean",
    icon: "images/gigocean.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2018",
    dateTo: "01-01-2022",
    link: "",
  },
  {
    role: "Senior Front End Developer",
    company: "Icon Agency",
    icon: "images/iconagency.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-12-2016",
    dateTo: "01-02-2021",
    link: "https://iconagency.com.au/",
  },
  {
    role: "Front End Developer",
    company: "IO Stuidos LTD",
    icon: "images/iostudios.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-06-2013",
    dateTo: "01-10-2016",
    link: "https://www.iostudios.co.uk/",
  },
  {
    role: "Web Developer",
    company: "NFU Mutual",
    icon: "images/nfumutual.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-09-2007",
    dateTo: "01-06-2013",
    link: "https://www.nfumutual.co.uk/",
  },
];
