import * as type from "@config";

export const EXPERIENCE = [
  {
    role: "Lead Frontend Engineer",
    company: "Lyka",
    icon: "images/lyka_logo.png",
    type: "Full-time",
    country: "Australia",
    dateFrom: "01-23-2023",
    dateTo: null,
    link: "https://lyka.com.au/",
    stack: [
      type.NUXT2,
      type.NUXT3,
      type.JS,
      type.TS,
      type.TAILWIND,
      type.BOOTSTRAP5,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Founder",
    company: "pixel61",
    icon: "images/pixel61_logo.png",
    type: "Part-time",
    country: "Australia",
    dateFrom: "09-30-2021",
    dateTo: null,
    link: "https://pixel61.com/",
    stack: [
      type.VUE3,
      type.NUXT3,
      type.JS,
      type.TS,
      type.TAILWIND,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Senior Frontend Developer",
    company: "mod.io",
    icon: "images/modio_logo.jpeg",
    type: "Full-time",
    country: "Australia",
    dateFrom: "02-01-2021",
    dateTo: "01-13-2023",
    link: "https://mod.io/",
    stack: [type.VUE3, type.JS, type.TAILWIND, type.HTML, type.CSS, type.SCSS],
  },
  {
    role: "Co-Founder & Director",
    company: "Linked Entity Limted",
    icon: "images/linkedentity_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2016",
    dateTo: "05-01-2022",
    link: "http://www.linkedentity.com/",
    stack: [
      type.WORDPRESS,
      type.JS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Co-Founder & Director",
    company: "Gig Ocean",
    icon: "images/gigocean_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2018",
    dateTo: "01-01-2022",
    link: "",
    stack: [
      type.VUE2,
      type.JS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Senior Frontend Developer",
    company: "Icon Agency",
    icon: "images/iconagency_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "12-01-2016",
    dateTo: "02-01-2021",
    link: "https://iconagency.com.au/",
    stack: [
      type.VUE2,
      type.JS,
      type.JQUERY,
      type.WORDPRESS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Frontend Developer",
    company: "IO Stuidos LTD",
    icon: "images/iostudios_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "06-01-2013",
    dateTo: "10-01-2016",
    link: "https://www.iostudios.co.uk/",
    stack: [
      type.JS,
      type.JQUERY,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.FOUNDATION,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Web Developer",
    company: "NFU Mutual",
    icon: "images/nfumutual_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "09-01-2007",
    dateTo: "06-01-2013",
    link: "https://www.nfumutual.co.uk/",
    stack: [type.JS, type.HTML, type.CSS],
  },
];
