import * as type from "@config";

export const EXPERIENCE = [
  {
    role: "Lead Frontend Engineer",
    company: "Lyka",
    icon: "images/lyka_logo.png",
    type: "Full-time",
    country: "Australia",
    dateFrom: "01-23-2023",
    dateTo: null,
    link: "https://lyka.com.au/",
    blurb:
      "<p>Lead Frontend Engineer | Lyka | People Manager (5 Engineers)</p><p>In this diverse role, I oversee projects, manage resources, and prioritise timely project delivery. Collaborating with fellow lead engineers, I nurture a culture of success, utilising my leadership, technical expertise, and robust project coordination skills. Together, we achieve outstanding outcomes, surpassing expectations and propelling the team towards excellence. </p>",
    stack: [
      type.NUXT2,
      type.NUXT3,
      type.JS,
      type.TS,
      type.TAILWIND,
      type.BOOTSTRAP5,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Founder",
    company: "pixel61",
    icon: "images/pixel61_logo.png",
    type: "Part-time",
    country: "Australia",
    dateFrom: "09-30-2021",
    dateTo: null,
    link: "https://pixel61.com/",
    blurb: "",
    stack: [
      type.VUE3,
      type.NUXT3,
      type.JS,
      type.TS,
      type.TAILWIND,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Senior Frontend Developer",
    company: "mod.io",
    icon: "images/modio_logo.jpeg",
    type: "Full-time",
    country: "Australia",
    dateFrom: "02-01-2021",
    dateTo: "01-13-2023",
    link: "https://mod.io/",
    blurb:
      "<p>Frontend Developer | mod.io | Remote Team of 35 (17 Engineers) | Specialising in UGC Support for Games | People Manager (2 Engineers)</p><p>In a global remote team, I helped drive the frontend development for mod.io, collaborating with backend and design teams to ensure seamless browsing on all devices. Main responsibilities for, leading the monetisation section's frontend development. Previously, I had successfully delivered Vue3 & TailwindCSS-based v2 project with a 3-member frontend team. Additionally, mentoring juniors, conducting PR reviews and hold regular guild meetings to ensure project consistency and growth.</p>",
    stack: [type.VUE3, type.JS, type.TAILWIND, type.HTML, type.CSS, type.SCSS],
  },
  {
    role: "Co-Founder & Director",
    company: "Linked Entity Limted",
    icon: "images/linkedentity_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2016",
    dateTo: "05-01-2022",
    blurb:
      "<p>Co-Founder & Director | Web Development Company | Established 2016 | Expertise in WordPress, Shopify, Vue.js & .NET Core</p><p>Passionate about development, I co-founded a successful UK-based web development company in 2016 with two fellow developers. Specialising in WordPress, Shopify, and online software, we've delivered multiple projects, including e-commerce sites and an innovative Vue.js & .NET Core-based online community for the music industry. </p>",
    link: "http://www.linkedentity.com/",
    stack: [
      type.WORDPRESS,
      type.JS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Co-Founder & Director",
    company: "Gig Ocean",
    icon: "images/gigocean_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "01-01-2018",
    dateTo: "01-01-2022",
    link: "",
    blurb: "",
    stack: [
      type.VUE2,
      type.JS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Senior Frontend Developer",
    company: "Icon Agency",
    icon: "images/iconagency_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "12-01-2016",
    dateTo: "02-01-2021",
    link: "https://iconagency.com.au/",
    blurb:
      "<p>Lead Developer | Icon Agency, Melbourne | Specialising in High-End Websites & Online Software</p><p>Led a team in building a large-scale Vue.js component library for the Australian Department of Defence, used to revamp over 150 sites. Successfully managed frontend developers, pull requests, and code reviews.</p><p>Delivered projects for prestigious clients like the Australian Airforce and Maurice Blackburn, using tailored development stacks for each project. Collaborated with cross-functional teams, including Backend Developers, UX/UI Designers, and Account Managers. </p>",
    stack: [
      type.VUE2,
      type.JS,
      type.JQUERY,
      type.WORDPRESS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Frontend Developer",
    company: "IO Stuidos LTD",
    icon: "images/iostudios_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "06-01-2013",
    dateTo: "10-01-2016",
    link: "https://www.iostudios.co.uk/",
    blurb:
      "<p>Frontend Developer | Small Team of 7 Devs, 2 Designers, 2 Frontend, 3 Backend | Website & Mobile App Specialist</p><p>I helped transform Web Designers' visions into seamless websites, ensuring consistency in look, feel, and functionality across major web and mobile browsers. Expertise in responsive web design & bespoke software. </p>",
    stack: [
      type.JS,
      type.JQUERY,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.FOUNDATION,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    role: "Web Developer",
    company: "NFU Mutual",
    icon: "images/nfumutual_logo.jpeg",
    type: "Full-time",
    country: "United Kingdom",
    dateFrom: "09-01-2007",
    dateTo: "06-01-2013",
    link: "https://www.nfumutual.co.uk/",
    blurb:
      "<p>Junior Frontend Developer | NFU (National Farmers' Union)</p><p>Part of a 7-member team, crafting bespoke web apps for internal NFU clients. Developed diverse sites and animations using HTML, CSS, JavaScript, and Flash, ranging from basic forms to SQL-backed full-fledged applications. Improved internal processes with efficient solutions. </p>",
    stack: [type.JS, type.HTML, type.CSS],
  },
];
