import * as type from '../config'

export const EXPERIENCE = [
  {
    company: 'Butternut Box',
    icon: 'images/butternut_box_logo.webp',
    type: 'Full-time',
    country: 'United Kingdom',
    attendance: 'Remote',
    link: [
      { text: 'Butternut Box', link: 'https://butternutbox.com/' },
    ],
    positions: [
      {
        role: 'Senior Frontend Engineer',
        dateFrom: '08/04/2025',
        dateTo: null,
      },
    ],
    blurb: [
      'As a Senior Frontend Engineer at Butternut Box, I work on rebuilding the main customer-facing website using React and Next.js, alongside a modern CMS setup with Storyblok. The focus of my role is delivering robust, scalable frontend solutions while improving performance, maintainability, and overall developer experience.',
      'While this is an individual contributor role, I regularly draw on my broader experience to help shape architecture decisions, identify potential issues early, and solve complex frontend problems pragmatically. I work closely with designers, product, and backend engineers to ensure the implementation aligns with both user needs and long-term technical goals.',
      'AI tooling (primarily Claude) is used day-to-day to support development, speed up iteration, and reduce cognitive load, while maintaining a strong focus on code quality and clarity.',
    ],
    stack: [
      type.REACT,
      type.NEXTJS,
      type.JS,
      type.TS,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
  {
    company: 'Lyka',
    icon: 'images/lyka_logo.webp',
    type: 'Full-time',
    country: 'Australia',
    attendance: 'Remote',
    link: [
      { text: 'Lyka', link: 'https://lyka.com.au/' },
      { text: 'Component Library', link: 'https://lyka-pet-food.github.io/lyka-common/?path=/docs/welcome--docs' },
    ],
    positions: [
      {
        role: 'Staff Engineer (UI)',
        dateFrom: '04/01/2024',
        dateTo: '05/01/2025',
      },
      {
        role: 'Lead Frontend Engineer',
        dateFrom: '01/01/2023',
        dateTo: '04/02/2024',
      },
    ],
    blurb: [
      'As a Staff / Lead Frontend Engineer at Lyka, I led the development of a company-wide design system and component library in close collaboration with the Design Lead. The goal was to create a single, scalable foundation for all frontend work, ensuring consistency, accessibility, performance, and ease of use across teams.',
      'I built the component library from the ground up as a private NPM package, defining standards around responsiveness, theming, accessibility, testing, versioning, and contribution workflows. This significantly improved developer experience and enabled teams to move faster without sacrificing quality.',
      'Alongside the technical work, I supported and mentored frontend engineers across multiple squads through regular guidance, PR reviews, and an open-door approach to problem solving. I also set up and ran a Design System / Component Library guild to encourage adoption, shared ownership, and cross-team collaboration.',
      'At a leadership level, I worked closely with engineering leadership and stakeholders to help shape frontend direction, improve processes, and align technical decisions with broader business goals.',
    ],
    stack: [
      type.COMPLIB,
      type.DESIGNSYS,
      type.NUXT2,
      type.NUXT3,
      type.JS,
      type.TS,
      type.TAILWIND,
      type.BOOTSTRAP5,
      type.HTML,
      type.CSS,
      type.SCSS,
      type.PEOPLE,
    ],
  },
  {
    company: 'Band Me Up',
    icon: 'images/band_me_up.webp',
    type: 'Part-time',
    country: 'Australia / United Kingdom',
    attendance: 'Remote',
    link: 'https://bandmeup.com/',
    positions: [
      {
        role: 'Founding Engineer',
        dateFrom: '09/01/2024',
        dateTo: null,
      },
    ],
    blurb: [
      'Band Me Up is a self-initiated SaaS product built end to end, from initial concept through to production. I designed and implemented the frontend architecture, UI patterns, and core application structure, focusing on maintainability, clarity, and long-term iteration rather than speed alone.',
      'The product includes authenticated user flows, dynamic data-driven pages, and admin-style interfaces, requiring careful state management and reusable component patterns. I approached the build with the same principles used in larger production systems: clear separation of concerns, scalable component structures, and predictable styling and layout conventions.',
      'As the sole engineer, I handled technical decision-making across the stack boundaries I interact with most closely, including frontend architecture, API integration, build tooling, and deployment considerations. The project continues to evolve incrementally, with changes driven by real usage, feedback, and ongoing learning rather than a fixed roadmap.',
    ],
    stack: [
      type.VUE3,
      type.TS,
      type.SUPABASE,
      type.TAILWIND,
      type.HTML,
      type.CSS,
    ],
  },
  {
    company: 'mod.io',
    icon: 'images/modio_logo.webp',
    type: 'Full-time',
    country: 'Australia',
    attendance: 'Remote',
    link: 'https://mod.io/',
    positions: [
      {
        role: 'Senior Frontend Engineer',
        dateFrom: '02/01/2021',
        dateTo: '01/01/2023',
      },
    ],
    blurb: [
      'As part of a fully remote, globally distributed team, I led frontend development across large parts of the mod.io platform, working closely with backend engineers and designers to deliver a responsive, accessible product used across web and embedded surfaces.',
      'I built the frontend architecture from the ground up, including an internal component library that enabled consistency, accessibility, and faster development across the team. A significant focus of my work was leading the frontend development of the monetisation area, coordinating with product and backend teams to deliver complex, state-heavy UI with a strong focus on performance and usability.',
      'Alongside hands-on development, I supported the wider frontend team through mentoring, PR reviews, and regular guild meetings, helping to maintain shared standards and improve overall code quality. I worked primarily on the Vue 3 and Tailwind-based v2 rebuild, contributing both to day-to-day delivery and longer-term frontend direction',
    ],
    stack: [
      type.COMPLIB,
      type.VUE3,
      type.JS,
      type.TAILWIND,
      type.HTML,
      type.CSS,
      type.PEOPLE,
    ],
  },
  {
    company: 'Icon Agency',
    icon: 'images/iconagency_logo.webp',
    type: 'Full-time',
    country: 'Australia',
    attendance: 'Hybrid',
    link: 'https://iconagency.com.au/',
    positions: [
      {
        role: 'Senior Frontend Developer',
        dateFrom: '12/01/2016',
        dateTo: '02/01/2021',
      },
    ],
    blurb: [
      'Worked as a senior frontend engineer on large-scale, long-running client projects, with a strong focus on component reuse, consistency, and maintainability across teams and codebases.',
      'Led frontend development on a Vue.js-based component library for the Australian Department of Defence, used to rebuild and standardise over 150 websites. This involved defining component patterns, maintaining shared styles and behaviours, and supporting other developers adopting the library across multiple projects.',
      'Regularly collaborated with backend engineers, designers, and account managers to deliver complex client work, balancing technical constraints with design and delivery timelines. Took responsibility for code quality through pull request reviews, frontend guidance, and day-to-day technical decision-making.',
      'Delivered work for high-profile clients including the Australian Air Force and Maurice Blackburn, adapting frontend approaches and tooling depending on project needs while maintaining a consistent level of quality and accessibility.',
    ],
    stack: [
      type.COMPLIB,
      type.VUE2,
      type.JS,
      type.JQUERY,
      type.WORDPRESS,
      type.BOOTSTRAP3,
      type.BOOTSTRAP4,
      type.HTML,
      type.CSS,
      type.SCSS,
    ],
  },
]
